version: 2
updates:
  - package-ecosystem: "cargo"
    directories: 
      - "/"
      - "/quests/0-hello-world"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      go-minor-and-patch:
        applies-to: version-updates
        update-types:
        - "patch"
        - "minor"
      go-major:
        applies-to: version-updates
        update-types:
        - "major"
  - package-ecosystem: "npm"
    directories: 
      - "/_client"
      - "/_squirtle"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        update-types:
        - "patch"
        - "minor"
      npm-major:
        applies-to: version-updates
        update-types:
        - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      all-actions:
        applies-to: version-updates
        patterns: [ "*" ]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      all-docker:
        applies-to: version-updates
        patterns: [ "*" ]